name: Update this repo's README with blog posts

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://www.lolloandr.com/blog/index.xml
          readme-section: feed
          branch: main
